name: java workflow
run-name: Used to test java applications, triggered by @${{ github.actor }}
on:
  push:
    branches: 
      - main

concurrency: 
  cancel-in-progress: true
  group: java-${{ github.workflow }}-${{ github.head_ref }}

jobs:
  javajob:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: |
          echo "Job completed"
  