name: Slack-notification-testing
run-name: We are testing slack notifications, Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
  cancel-in-progress: true
  group: slack-${{ github.workflow }}-${{ github.head_ref }}

defaults:
  run:
    shell: bash

jobs:
  slack-first-msg:
    name: Slacknotification
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-deployments
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png?size=48
          SLACK_TITLE: We are Testing Slack notifications
          SLACK_MESSAGE: 'Started: Workflow ${{ github.workflow }}, Runid: ${{ github.run_id }}, Run Number: ${{ github.run_number }}, RUNURL : ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}, Triggerd by @${{ github.actor }}, Event: ${{ github.event_name }}, RunnerUsed: ${{ runner.os }}'
          SLACK_USERNAME: githubbot
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_FOOTER: Powered by Github Slack Integration
  find_commit_short_sha:
    runs-on: ubuntu-22.04
    needs:
      - slack-first-msg
    steps:
      - run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> "GITHUB_ENV" 
  buildjob:
    runs-on: ubuntu-22.04
    needs: 
      - slack-first-msg
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm ci
  publish_to_docker:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          # registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
          images: ${{ secrets.DOCKER_USERNAME }}/courserepo
          tags: |
            type=raw,value=${{ env.SHORT_SHA }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  publish_to_ghcr:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          # registry: ${{ secrets.HARBOR_REGISTRY }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ env.SHORT_SHA }}
      - uses: docker/build-push-action@v5
        with:          
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  deploy_job:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
      - publish_to_docker
    steps:
      - run: |
          echo "Deploying"
          sleep 1m
  
  register-dora-metrics:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    environment: development
    needs: 
      - publish_to_ghcr
      - deploy_job
    steps:
      - run: |
          curl -X POST \
          'https://app.sleuth.io/api/1/deployments/sidhusaiprasanthorg/courserepo/register_deploy' \
            -H 'Authorization: Bearer ${{ secrets.SLEUTH_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{
            "sha": "${{ env.SHORT_SHA }}",
            "environment": "${{ vars.ENVIRON }}"
          }'


  
  
  slack-completed-msg:
    name: Slacknotification-2
    needs: 
      - slack-first-msg
      - deploy_job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-deployments
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png?size=48
          SLACK_TITLE: We are Testing Slack notifications
          SLACK_MESSAGE: '${{ github.run_id }},${{ github.run_number }},RUNURL : ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} - *${{ job.status }}:* '
          SLACK_USERNAME: githubbot
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_FOOTER: Powered by Github Slack Integration

