name: Slack-notification-testing
run-name: We are testing slack notifications, Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore: 
      - 'README.md'
  workflow_dispatch:
  pull_request:

concurrency: 
  cancel-in-progress: true
  group: slack-${{ github.workflow }}-${{ github.head_ref }}

defaults:
  run:
    shell: bash

jobs:
  slack-first-msg:
    name: Slacknotification
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-deployments
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png?size=48
          SLACK_TITLE: We are Testing Slack notifications
          SLACK_MESSAGE: 'Started: Workflow ${{ github.workflow }}, Runid: ${{ github.run_id }}, Run Number: ${{ github.run_number }}, RUNURL : ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}, Triggerd by @${{ github.actor }}, Event: ${{ github.event_name }}, RunnerUsed: ${{ runner.os }}'
          SLACK_USERNAME: githubbot
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_FOOTER: Powered by Github Slack Integration
  buildjob:
    runs-on: ubuntu-22.04
    needs: 
      - slack-first-msg
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm ci
  publish_to_docker:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: sidhugithubaction/sidhu-commonactions-workflows/customactions/to-publish-to-docker@v1.0.1
        with:
          image_name: courserepo
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
      # - uses: actions/checkout@v4
      # - run: |
      #     echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
      #     echo $SHORT_SHA
      # - uses: docker/login-action@v3
      #   with:
      #     # registry: ${{ secrets.HARBOR_REGISTRY }}
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - uses: docker/metadata-action@v5
      #   id: meta
      #   with:
      #     # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
      #     images: ${{ secrets.DOCKER_USERNAME }}/courserepo
      #     tags: |
      #       ${{ env.SHORT_SHA }}
      # - uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
  publish_to_ghcr:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: sidhugithubaction/sidhu-commonactions-workflows/customactions/to-publish-to-ghcr@v1.0.1
        with:
          ghcr_password: ${{ secrets.GHCR_TOKEN }}
      # - uses: actions/checkout@v4
      # - run: |
      #     echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
      #     echo $SHORT_SHA
      # - uses: docker/login-action@v3
      #   with:
      #     # registry: ${{ secrets.HARBOR_REGISTRY }}
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_TOKEN }}
      # - uses: docker/metadata-action@v5
      #   id: meta
      #   with:
      #     # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
      #     images: ghcr.io/${{ github.repository }}
      #     tags: |
      #       ${{ env.SHORT_SHA }}
      # - uses: docker/build-push-action@v5
      #   with:          
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
  deploy_job:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
      - publish_to_docker
    steps:
      - run: |
          echo "Deploying"
          sleep 1m
  
  register-dora-metrics:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    environment: development
    needs: 
      - publish_to_ghcr
      - deploy_job
    steps:
      - run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
          echo $SHORT_SHA
      - run: |
          curl -X POST \
          'https://app.sleuth.io/api/1/deployments/sidhusaiprasanthorg/courserepo/register_deploy' \
            -H 'Authorization: Bearer ${{ secrets.SLEUTH_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{
            "sha": "${{ env.SHORT_SHA }}",
            "environment": "${{ vars.ENVIRON }}"
          }'

  publish-docker-staging:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
    if: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-rc') }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
          echo $SHORT_SHA
      - uses: docker/login-action@v3
        with:
          # registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
          images: ${{ secrets.DOCKER_USERNAME }}/courserepo
          tags: |
            ${{ env.SHORT_SHA }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  publish_to_ghcr_staging:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-rc')
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
          echo $SHORT_SHA
      - uses: docker/login-action@v3
        with:
          # registry: ${{ secrets.HARBOR_REGISTRY }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ env.SHORT_SHA }}
      - uses: docker/build-push-action@v5
        with:          
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy_to_staging:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-rc')
    environment:
      name: staging
    needs:
      - publish-docker-staging
      - publish_to_ghcr_staging
    steps:
      - run: |
          echo "Deploying to ${{ vars.ENVIRON }}"

  register-dora-metrics_staging:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-rc')
    runs-on: ubuntu-22.04
    environment:
      name: staging
    needs: 
      - publish-docker-staging
      - publish_to_ghcr_staging
      - deploy_to_staging
    steps:
      - run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
          echo $SHORT_SHA
      - run: |
          curl -X POST \
          'https://app.sleuth.io/api/1/deployments/sidhusaiprasanthorg/courserepo/register_deploy' \
            -H 'Authorization: Bearer ${{ secrets.SLEUTH_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{
            "sha": "${{ env.SHORT_SHA }}",
            "environment": "${{ vars.ENVIRON }}"
          }'

  release_to_staging:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-rc')
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
      issues: write
      pull-requests: write
    needs: 
      - register-dora-metrics_staging
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Dockerfile
            harbordocs.md
            package.json
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          prerelease: true


  # Production ###################

  publish-docker-production:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc') }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
          echo $SHORT_SHA
      - uses: docker/login-action@v3
        with:
          # registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
          images: ${{ secrets.DOCKER_USERNAME }}/courserepo
          tags: |
            ${{ env.SHORT_SHA }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  publish_to_ghcr_production:
    runs-on: ubuntu-22.04
    needs: 
      - buildjob
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
          echo $SHORT_SHA
      - uses: docker/login-action@v3
        with:
          # registry: ${{ secrets.HARBOR_REGISTRY }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ env.SHORT_SHA }}
      - uses: docker/build-push-action@v5
        with:          
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy_to_prod:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
    environment:
      name: production
    needs:
      - publish-docker-production
      - publish_to_ghcr_production
    steps:
      - run: |
          echo "Deploying to ${{ vars.ENVIRON }}"


  register-dora-metrics_production:
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
    runs-on: ubuntu-22.04
    environment:
      name: production
    needs: 
      - publish-docker-production
      - publish_to_ghcr_production
      - deploy_to_prod
    steps:
      - run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
          echo $SHORT_SHA
      - run: |
          curl -X POST \
          'https://app.sleuth.io/api/1/deployments/sidhusaiprasanthorg/courserepo/register_deploy' \
            -H 'Authorization: Bearer ${{ secrets.SLEUTH_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{
            "sha": "${{ env.SHORT_SHA }}",
            "environment": "${{ vars.ENVIRON }}"
          }'

  release_to_prod:
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
      issues: write
      pull-requests: write
    needs: 
      - register-dora-metrics_production
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Dockerfile
            harbordocs.md
            package.json
          token: ${{ secrets.GITHUB_TOKEN }}   

  



  ########################
  
  slack-completed-msg:
    name: Slacknotification-2
    needs: 
      - register-dora-metrics
      - register-dora-metrics_staging
      - register-dora-metrics_production
      - release_to_prod
    # if: ${{ always() }}
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-deployments
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png?size=48
          SLACK_TITLE: We are Testing Slack notifications
          SLACK_MESSAGE: '${{ github.run_id }},${{ github.run_number }},RUNURL : ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} - *${{ job.status }}:* '
          SLACK_USERNAME: githubbot
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_FOOTER: Powered by Github Slack Integration

  slack-custom:
    name: Slack-custom
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    needs: 
      - slack-completed-msg
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-slack-notification
        with:
            deployment_name: ${{ github.repository }}
            slack_channels: 'C06TCB99PE0'
            slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}


